# -*- coding: utf-8 -*-
"""MINOR PROJECT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13ZerzpuEUjkZ33JhsS9St-sGZKmqYX_a
"""

# USER CREDENTIAL VERIFICATION

import string
import time
print("---- USER CREDENTIAL VERIFICATION SYSTEM ----".center(90))
time.sleep(1)
print("\n")
choice=input("Select Mode of Authentication (1 or 2)\n1.Phone Number\n2.Email Id\n")


#Phone Number Validation
def ph_no(no):
  if no.isdigit()==False:
    if len(no)!=10:
      return "Phone number can only contain  digits and must be 10 digits long."      # when input is neither a digit nor 10 characters long
    else:
      return "Phone number can only contain digits."

  if len(no)!=10:
    if len(no)>10:
      return "Phone number cannot exceed 10 digits."
    else:
      return "Insufficient digits. Phone number must be 10 digits long."

  if no[0]=='0':
      return "Phone number cannot start with 0."

  return True



#Email Validation
def email(id):
  if len(id)>254:        #To check the total length of the email address(id)
    return False

  if ' ' in id:
    return False

  d1=id.split('@')      #Splitting local and domain part
  if len(d1)!=2:
    return False

  local=d1[0]           #Assigning variables to local and domain part
  domain=d1[1]

  if len(local)>64:
    return False
  if '_'in domain:
    return False
  if len(domain)<7:
    return False

  #Local Part Validation
  if '"' in local or '\\' in local:
      return False

  special_chars = "!#$%&'*+-/=?^_{|}~"
  all_chars=string.ascii_letters+string.digits+special_chars+'.'   #Collection of strings that are allowed to be in local part
  for i, char in enumerate(local):                                 #Iterates through every character of local part
    if char not in all_chars:
      return False

    if char=='.':
      if i==0 or i==len(local)-1:                                  #To check for the conditon that '.' doesnt appear at the first or the last position of local part
        return False
      if i+1 <len(local) and local[i+1]=='.':                      #(iterates throughout the local part)To check for the conditon that '.' doesnt appear at alternate positions
        return False


  if not local:                                                    #To check if local part is empty
    return False

  #Domain Part Validation
  if '.' not in domain:
    return False

  allowed_chars2= string.ascii_letters + string.digits + '-'
  d2=domain.split('.')                                        #Separates domain and top level domain
  if len(d2)<2:
    return False

  top=d2[-1]                                                  #Assigning variable to top level domain
  if len(top)<2:
    return False

  for top_domain in (d2):                                     #Iterates through each character of domain (which is a list)
    if not top_domain:
      return False

  if not top_domain[0].isalnum() or not top_domain[-1].isalnum(): #To check if top level domain starts and ends with an alphabet or digit
    return False

  for char in top_domain:
    if char not in allowed_chars2:
      return False

  if top.lower() not in ['org','com','edu']:                 #To check for valid top level domain labels(also ruling out case-sensitivity)
    return False


  return True


#Password Validation
def password(pin):
  if len(pin)<8:
    return "Password must be at least 8 characters long"

  digits=False                                        #Setting flags to check for each condition
  lowercase=False
  uppercase=False
  special=False

  for char in pin:                                    #Chcking for atleast one occurrence of digit,special characters,uppercase and lowercase letters by iterating through the string
    if char.isdigit():
      digits=True
    elif char.isupper():
      uppercase=True
    elif char.islower():
      lowercase=True
    elif char in string.punctuation:
      special=True

  if not digits:
    return "Password must contain at least one digit."
  if not lowercase:
    return "Password must contain at least one lowercase letter."
  if not uppercase:
    return "Password must contain at least one uppercase letter."
  if not special:
    return "Password must contain at least one special character."

  return True



if choice!='1' and choice!='2':
  while True:
    print("\nInvalid Choice\n")
    choice=input("Select Mode of Authentication (1 or 2)\n1.Phone Number\n2.Email Id\n")
    if choice=='1' or choice=='2':
      break


if choice == '1':                                           #Executing specific functions according to the user's choice
  while True:
    number=input("Enter Phone number: ")
    outcome1=ph_no(number)
    if outcome1==True:
      break
    else:
      print("Invalid Input!")
      print(outcome1)

elif choice=='2':
    while True:
      address=input("Enter Email Id: ")
      outcome2=email(address)
      if outcome2==True:
        break
      else:
        print("Invalid Email Address. Please Try Again.\n")



while True:
  user_password=input("Enter Password: ")
  print("\n")
  outcome3=password(user_password)
  if outcome3==True:
    for char in "LOGGING IN... ":                         #Simulating a "logging in" animation 
      print(char, end="", flush=True)
      if char!= ' ':
        time.sleep(0.21)
    print("\n")
    print("---- AUTHENTICATION SUCCESSFUL ----".center(85))
    break
  else:
    print("Invalid Input!")
    print(outcome3)
